### ISSUE TITLE
Issues with Paged Output

### ISSUE THREAD

**Issue by clwill** [billerickson/Display-Posts-Transient-Cache#1]
When I use this with a page that has nothing but a DPS shortcode on it, and the output is paged, when I go to any of the later pages, it dumps what appears to be a JS object on the screen. The first page is fine, the later pages all seem to generate this dump.

**Comment by billerickson** [comment]
Are you trying to use this in combination with the [Display Posts Pagination](https://github.com/billerickson/Display-Posts-Pagination) extension? You shouldn't try to use this with pagination because it will serve the same results regardless of the page (it's pulling the cached copy). 

Can you provide a screenshot of what you're seeing and the shortcode you're using?

**Comment by clwill** [comment]
Thanks for your reply, Bill. Yes, I am using it with pagination (your extension), and -- in the cold light of day -- it makes sense why it wouldn't work. I wonder if the pagination extension could tack the page number onto a transient key if it finds that argument (it's already filtering the arguments). Hmmm, that *might* work. I'm playing with it, I'll let you know if I have any success :)

**Comment by clwill** [comment]
Bill, I think I have a small change to the Caching extension that works in conjunction with the pagination extension. Just a few additional lines to the "transient_cache" function in the BE_DPS_Transient_Cache class. To wit:

	function transient_cache( $output, $atts ) {
		if( empty( $atts['transient_key'] ) || empty( $atts['transient_expiration'] ) )
			return $output;

		$key = $this->transient_key( $atts['transient_key'] );
			
		if( !empty( $atts['pagination'] ) ) {
			$format = 'dps_paged';
			if( intval( $atts['pagination'] ) > 1 )
				$format .= '_' . intval( $atts['pagination'] );

			if( ! empty( $_GET[ $format ] ) )
				$key .= "-" . intval( $_GET[ $format ] );
		}
		
		$cache = get_transient( $key );
		if( false === $cache ) {
			$expiration = $this->transient_expiration( $atts['transient_expiration'] );
			unset( $atts['transient_key'] );
			unset( $atts['transient_expiration'] );
			$cache = be_display_posts_shortcode( $atts );
			set_transient( $key, $cache, $expiration );
		}
		return $cache;
	}

It just tacks the page number on the cache key if you're doing pagination. This appears to work for me, although I have only tried it on a couple of cases.

Hope this helps,
Chris

**Comment by clwill** [comment]
Hmmm, check that. This seems to work about 80% of the time, but every now and then the pagination links go all wonky, and start referring to some "wp-json" link and starts dumping JSON code. 

The links go to this kind of thing:

`http://christophers-mac-pro.local:5757/wp-json/wp/v2/pages/665/?dps_paged=2&_locale=user`

Here's the front bit of what I'm seeing output:

<code>{"id":665,"date":"2019-06-24T13:53:08","date_gmt":"2019-06-24T21:53:08","guid":{"rendered":"http:\/\/localhost\/~chris\/clwill\/?page_id=665"},"modified":"2019-07-29T11:34:07","modified_gmt":"2019-07-29T19:34:07","slug":"articles","status":"publish","type":"page","link":"http:\/\/localhost\/~chris\/clwill\/articles\/","title":{"rendered":"Articles"},"content":{"rendered":"<div class=\"display-posts-listing layout-article\"><article class=\"article-panel\">\n\t<div class=\"content clearfix\">\n\t\t<h2 class=\"title\"><a href=\"http:\/\/localhost\/~chris\/clwill\/post\/too-many-dealers-not-enough-customers\/\"></code> followed by the rest of the raw HTML for the page.

I'm not sure quite what's going on. Maybe it's related to CodeKit? And it's caching? Or what. When the links just include `?dps_paged=` and some page number, it all works great. And the pagination links are all OK.

But every now and then, the pagination links get all this `wp-json/...` on them and things go south.

I'll let you know when/if I figure this out.

**Comment by billerickson** [comment]
Yes, that approach would work well.
