### ISSUE TITLE
display-posts outpud different if cache activated

### ISSUE THREAD

**Issue by colomet** [billerickson/Display-Posts-Transient-Cache#2]
display-posts plugin works fine in our installation, but if activated with your cache plugin, the outpud is not as expected.
We did try to clear transcients and cache but nothing change.

We may do something wrong, maybe.

that´s our configuration

```
$key_pb_subtitle = get_post_meta( get_the_ID(), 'pb_subtitle', true );
// Check if the custom field has a value.
if ( empty( $key_pb_subtitle ) && is_singular('chapter')) {?>
<div class="display-posts-ul" >
<br>
<h2 data-type="subtitle">More topics</h2>
<?php echo do_shortcode( '[display-posts transient_key="be_display_posts-rand" transient_expiration="WEEK_IN_SECONDS" wrapper="ul" wrapper_class="display-posts-ul" exclude_current="true" post_type="chapter" post_status="publish" orderby="rand" order="ASC"]' );
}
?>
```

**Comment by billerickson** [comment]
In what way is the output unexpected? 

I wouldn't recommend using the cache extension when doing orderby="rand". The cache will load the results once, save it in the database, and serve those same results every time until the cache expires (ex: WEEK_IN_SECONDS).  So the random order will only change once every week.

**Comment by colomet** [comment]
yea, the random is ok in such way. 

our problem is, we use a custom metabox with the meta field: pb_subtitle. And we organise the links by those metafields. But if we activate your extension, the values are not related to the metafield

**Comment by billerickson** [comment]
I don't see `$key_pb_subtitle` used in your shortcode.

If you are using that variable as one of the shortcode arguments, you'll want to make sure to include it as part of the transient key as well. For instance, if you have 5 different subtitles, you'd want 5 different transients used to store their related Display Posts output.

**Comment by colomet** [comment]
Sorry. my mistake, I did copy the wrong one

`[display-posts  wrapper="ul" wrapper_class="display-posts-ul" meta_key="pb_subtitle" meta_value="'. $subtitle . '" exclude_current="true" post_type="chapter" post_status="publish" orderby="title" order="ASC" ]`

that´s the one

**Comment by colomet** [comment]
it works without the cache activated

**Comment by billerickson** [comment]
The results of that shortcode depend upon the subtitle you have specified. You need a unique key for every different subtitle used.

Your previous example used a single key (`be_display_posts-rand`).

You need something like: 

```
[display-posts  transient_key="dps_subtitle_' . $subtitle . '" transient_expiration="WEEK_IN_SECONDS" wrapper="ul" wrapper_class="display-posts-ul" meta_key="pb_subtitle" meta_value="'. $subtitle . '" exclude_current="true" post_type="chapter" post_status="publish" orderby="title" order="ASC" ]
```

So it uses a separate transient for each subtitle.
