### ISSUE TITLE
Can't verify if this is working

### ISSUE THREAD

**Issue by rsmith4321** [billerickson/Display-Posts-Transient-Cache#3]
I've installed the plugin and I have this in my shortcode `transient_key="home_page_recent_posts" transient_expiration="DAY_IN_SECONDS"` . I've also installed the transient manager plugin to check if the transients are being stored and I can't find any transients with my key. I've searched and can't find any evidence this is working. Can you let me know if I've done something wrong? I'm testing it here [https://www.ryansmithphotography.com](https://www.ryansmithphotography.com). Thanks!

**Comment by billerickson** [comment]
I can't verify it from the frontend, but you could look in the wp_options table to see if that transient is in there. 

The transient is used if your shortcode contains both the `transient_key` and `transient_expiration` parameters, which it sounds like you have done correctly.

**Comment by rsmith4321** [comment]
Thanks for the help. I actually realized it was because I had redis object
caching, it seems to store the transient in the redis cache and wasn't
viewable by the plugin I had installed. I can see it if I look in the redis
cache. Would you recommend to keep the transient caching installed even
when using object caching?

**Comment by billerickson** [comment]
I'm not very familiar with redis, but I think it provides a persistent object cache across pageviews. I'm not sure if a transient will necessarily improve the performance on a site with persistent object caching, but it won't hurt.
